---
title: "Reproducible Research: Peer Assessment 1"
author: "Dana Ostfeld""
date: "For project submission 11/16/14"
output: 
   html_document:
   keep_md: true
---

## Loading and preprocessing the data
```{r}
activ <- read.csv("activity.csv")
daily_steps <- tapply(activ$steps, activ$date, sum)
steps <- daily_steps[!is.na(daily_steps[])]
```

## What is mean total number of steps taken per day?
```{r meandailysteps}
hist(steps)
summary(steps)
dev.copy(png, file = "steps_histogram.png")
dev.off()
```

## What is the average daily activity pattern?

```{r mean_daily_activity}
activ2 <-activ[!is.na(activ[,1]),]
average_steps <- aggregate(activ2$steps, list(activ2$interval), mean)
colnames(average_steps)<- c("interval", "steps")
#Convert the military time to regular time, and add it to a new "time" column
average_steps$time <- as.POSIXct(average_steps$interval%/%100*3600+average_steps$interval%%100*60, "%H:%M:%S", origin = "2000-01-01 00:00:00")
library(ggplot2)
library(scales)
m <- qplot(time, steps, data = average_steps, geom = c("line"), main="Average Steps per Day, 10/12-11/12")
m+scale_x_datetime(breaks = date_breaks("120 min"), labels = date_format("%H:%M"))
dev.copy(png, file = "averagedailypattern.png")
dev.off()
average_steps$steps <- round(average_steps$steps, 3)
#Look at summary to find what the max steps are
summary(average_steps)
#Find what time of day the max steps (206.170) is
average_steps[average_steps$steps==206.170,]
```

## Imputing missing values
```{r imputing_missing_values}
na_count <- activ[is.na(activ[,1]),]
#count number of n/a rows
nrow(na_count)
# Devise strategy for imputing missing NAs
# I'll use the average daily steps to replace all NAs. The mean is provided in the summary data.
summary(activ)
#The summary data shows that the mean steps per day is 37.38
activ3 <- activ
#Next, create dataset with the NA values replaced with 37.38
activ3[is.na(activ3)] <- 37.38
par(mfrow = c(1, 2))
new_stps_mean<- aggregate(activ3$steps, list(activ3$date), mean)
colnames(new_stps_mean)<- c("date", "average steps")
hist(new_stps_mean[,2], xlab="mean number of steps per day", main="Mean Steps/Day")
new_stps_median<- aggregate(activ3$steps, list(activ3$date), median)
colnames(new_stps_median)<- c("date", "average steps")
hist(new_stps_median[,2], xlab="median steps per day", main="Median Steps/Day")
summary(new_stps_mean)
summary(new_stps_median)
dev.copy(png, file = "median_mean_w_nas_imputed.png")
dev.off()
#On most days, the most common # of steps per 5 minute interval is 0, so the median is often 0.
```

## Are there differences in activity patterns between weekdays and weekends?
```{r wkdys_v_wknds}
activ3$date <- as.Date(activ3$date)
#Let's make sure the date is now a date (not a factor)
str(activ3)
activ3$weekday<- weekdays(activ3$date)
#separate weekends from weekdays
activ3$day <- ifelse(activ3$weekday=="Sunday"|activ3$weekday=="Saturday", "Weekend", "Weekday") 

#find average steps for each 5-minute increment over the weekend
weekend <- subset(activ3, day=="Weekend")
wknd_stps <- aggregate(weekend$steps, list(weekend$interval), mean)
colnames(wknd_stps)<- c("interval", "steps")
wknd_stps$time <- as.POSIXct(wknd_stps$interval%/%100*3600+wknd_stps$interval%%100*60, "%H:%M:%S", origin = "2000-01-01 00:00:00")
wknd_stps$day <- "weekend"

#find average steps for each 5-minute increment during the week
weekday <- subset(activ3, day=="Weekday")
wk_stps <- aggregate(weekday$steps, list(weekday$interval), mean)
colnames(wk_stps)<- c("interval", "steps")
wk_stps$time <- as.POSIXct(wk_stps$interval%/%100*3600+wk_stps$interval%%100*60, "%H:%M:%S", origin = "2000-01-01 00:00:00")
wk_stps$day <- "weekday"

#combine weekend and weekdays and make graphs for each
all_steps <- rbind(wknd_stps, wk_stps)
week <- qplot(time, steps, data = all_steps, geom = c("line"), main="Average Weekday Steps per Day, Oct/12-Nov/12", facets = day~.)
week+scale_x_datetime(breaks = date_breaks("120 min"), labels = date_format("%H:%M"))
dev.copy(png, file = "wknd_v_wkdays.png")
dev.off()
```